### ISSUE TITLE
Fix Failing Tests

### ISSUE THREAD

**Issue by schretzilla** [schretzilla/Website-3.0#23]
### Description:
Issues when running npm run test

```
TypeError: fsevents is not a function
    at new FSEventsWatcher (/Users/greatscott/Development/scott/Website-3.0/node_modules/jest-haste-map/build/lib/FSEventsWatcher.js:162:20)
    at createWatcher (/Users/greatscott/Development/scott/Website-3.0/node_modules/jest-haste-map/build/index.js:1052:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/greatscott/Development/scott/Website-3.0/node_modules/jest-haste-map/build/index.js:1230:44)
    at /Users/greatscott/Development/scott/Website-3.0/node_modules/jest-haste-map/build/index.js:517:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/greatscott/Development/scott/Website-3.0/node_modules/jest-haste-map/build/index.js:193:24)
    at _next (/Users/greatscott/Development/scott/Website-3.0/node_modules/jest-haste-map/build/index.js:213:9)
npm ERR! code ELIFECYCLE
```

**Comment by schretzilla** [comment]
This was a local issue only that was resolved by removing xcode-select and reinstalling it
